### ISSUE TITLE
Create the skeleton of the project

### ISSUE THREAD

**Issue by aivinog1** [aivinog1/cv-react#1]
Let's create the skeleton of the project:
1. CI/CD - Travis, Rultor, publish at Github pages;
2. Create-react-app;
3. Codecov, tests;
etc..

**Comment by 0pdd** [comment]
@aivinog1 2 puzzles [#10](https://github.com/aivinog1/cv-react/issues/10), [#11](https://github.com/aivinog1/cv-react/issues/11) are still not solved.

**Comment by aivinog1** [comment]
Let's close this. Todos was created successfully.

**Comment by 0pdd** [comment]
@aivinog1 the puzzle [#11](https://github.com/aivinog1/cv-react/issues/11) is still not solved; solved: [#10](https://github.com/aivinog1/cv-react/issues/10).
